#! /bin/sh

bspc desktop ^1 -n "1"
bspc monitor -a "2" "3" "4" "5" "6" "7" "8" "9"

bspc config rule_command "$BSPWM_PATH/rules.sh"

bspc config border_width 2
bspc config window_gap 10
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config split_ratio 0.6180339887
bspc config focus_follows_pointer true

bspc config focused_border_color "#82B414"
bspc config normal_border_color "#FD971F"

bspc config top_padding 14

bspc control --subscribe > "$PANEL_FIFO" &

panel &
## Gammal
#sh "$BSPWM_PATH/bspwm_panel.sh" &

